#acm2108Òý½Å·ÖÅä
set_property IOSTANDARD LVCMOS33 [get_ports AD0_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports AD1_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports DA0_Clk]
set_property IOSTANDARD LVCMOS33 [get_ports DA1_Clk]
set_property IOSTANDARD LVCMOS33 [get_ports {AD0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD1[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA0_Data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA1_Data[7]}]

set_property PACKAGE_PIN V9 [get_ports {AD0[0]}]
set_property PACKAGE_PIN V10 [get_ports {AD0[1]}]
set_property PACKAGE_PIN W12 [get_ports {AD0[2]}]
set_property PACKAGE_PIN V12 [get_ports {AD0[3]}]
set_property PACKAGE_PIN AB12 [get_ports {AD0[4]}]
set_property PACKAGE_PIN AA12 [get_ports {AD0[5]}]
set_property PACKAGE_PIN AB11 [get_ports {AD0[6]}]
set_property PACKAGE_PIN AA11 [get_ports {AD0[7]}]

set_property PACKAGE_PIN W8 [get_ports {AD1[0]}]
set_property PACKAGE_PIN AA7 [get_ports {AD1[1]}]
set_property PACKAGE_PIN AA6 [get_ports {AD1[2]}]
set_property PACKAGE_PIN AB10 [get_ports {AD1[3]}]
set_property PACKAGE_PIN AB9 [get_ports {AD1[4]}]
set_property PACKAGE_PIN AA9 [get_ports {AD1[5]}]
set_property PACKAGE_PIN AA8 [get_ports {AD1[6]}]
set_property PACKAGE_PIN W6 [get_ports {AD1[7]}]

set_property PACKAGE_PIN Y5 [get_ports {DA0_Data[0]}]
set_property PACKAGE_PIN V7 [get_ports {DA0_Data[1]}]
set_property PACKAGE_PIN W7 [get_ports {DA0_Data[2]}]
set_property PACKAGE_PIN Y11 [get_ports {DA0_Data[3]}]
set_property PACKAGE_PIN Y10 [get_ports {DA0_Data[4]}]
set_property PACKAGE_PIN U10 [get_ports {DA0_Data[5]}]
set_property PACKAGE_PIN U9 [get_ports {DA0_Data[6]}]
set_property PACKAGE_PIN U12 [get_ports {DA0_Data[7]}]

set_property PACKAGE_PIN T6 [get_ports {DA1_Data[0]}]
set_property PACKAGE_PIN R6 [get_ports {DA1_Data[1]}]
set_property PACKAGE_PIN U4 [get_ports {DA1_Data[2]}]
set_property PACKAGE_PIN T4 [get_ports {DA1_Data[3]}]
set_property PACKAGE_PIN V4 [get_ports {DA1_Data[4]}]
set_property PACKAGE_PIN V5 [get_ports {DA1_Data[5]}]
set_property PACKAGE_PIN U5 [get_ports {DA1_Data[6]}]
set_property PACKAGE_PIN U6 [get_ports {DA1_Data[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property PACKAGE_PIN P20 [get_ports led]

set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_txd[0]}]

set_property PACKAGE_PIN U16 [get_ports {rgmii_rxd[3]}]
set_property PACKAGE_PIN W15 [get_ports {rgmii_rxd[2]}]
set_property PACKAGE_PIN Y14 [get_ports {rgmii_rxd[1]}]
set_property PACKAGE_PIN AA14 [get_ports {rgmii_rxd[0]}]

set_property PACKAGE_PIN V20 [get_ports {rgmii_txd[3]}]
set_property PACKAGE_PIN AA18 [get_ports {rgmii_txd[2]}]
set_property PACKAGE_PIN Y16 [get_ports {rgmii_txd[1]}]
set_property PACKAGE_PIN W18 [get_ports {rgmii_txd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rxdv]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_txen]
set_property PACKAGE_PIN W16 [get_ports rgmii_tx_clk]

set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rx_clk_i]

set_property IOSTANDARD LVCMOS33 [get_ports key_in]
set_property PACKAGE_PIN H18 [get_ports key_in]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets rgmii_rx_clk_i]


set_property PACKAGE_PIN V8 [get_ports AD0_CLK]
set_property PACKAGE_PIN W5 [get_ports AD1_CLK]

set_property PACKAGE_PIN U11 [get_ports DA0_Clk]
set_property PACKAGE_PIN Y6 [get_ports DA1_Clk]

set_property IOSTANDARD LVCMOS33 [get_ports eth_rstn]
set_property PACKAGE_PIN Y19 [get_ports eth_rstn]

set_property PACKAGE_PIN W17 [get_ports rgmii_rx_clk_i]
set_property PACKAGE_PIN Y15 [get_ports rgmii_rxdv]
set_property PACKAGE_PIN U15 [get_ports rgmii_txen]
